### ISSUE TITLE
Converti a UTF8

### ISSUE THREAD

**Issue by gsasoftware** [jmalarcon/FileEncodingConverter#2]
Cuando ejecuto el comando:
FileEncodingConverter.exe C:\FileEncodingConverter UTF8 *.xml /f
FileEncodingConverter.exe C:\FileEncodingConverter UTF8 *.xml

El xml no cambia de codificación y sigue siendo ISO-8859-1

¿Porque puede ser?

**Comment by jmalarcon** [comment]
Hola:

Antes de nada: ¿estás seguro de que el archivo está codificado como ISO-8859-1 o es que dentro en el XML pone que tiene esa codificación? Ten en cuenta que el programa solo cambia la codificación del archivo en sí, pero no toca los contenidos de éste. Si el XML indica eso y lo recodificas, tendías que cambiar a mano la codificación indicada para que ponga UTF-8.

Puedes ver fácilmente su codificación con Notepad++-

Si realmente la codificación física del archivo es la correcta pero no los transforma, adjúntame un archivo de ejemplo y le echo un vistazo cuando pueda e intento ver qué está pasando ¿de acuerdo?

Saludos

**Comment by gsasoftware** [comment]
Muchas gracias por responder. Los tiros iban por lo que me has comentado.

Alberto Garcia Larequi
--------------------------------------
Albertogarcia.net - mi blog
